name: Security Audit

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run weekly on Monday at 9AM UTC
    - cron: '0 9 * * 1'

jobs:
  security-audit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run security audit
      run: npm audit --audit-level moderate
      
    - name: Check for vulnerabilities
      run: |
        if npm audit --audit-level high --json | jq '.vulnerabilities | length' | grep -v '^0$'; then
          echo "High severity vulnerabilities found!"
          npm audit --audit-level high
          exit 1
        fi
        
      
    - name: Build project
      run: npm run build
      
    - name: Test build artifacts
      run: |
        # Check that sensitive information isn't exposed in build
        if grep -r "SENDGRID_API_KEY\|password\|secret" dist/ --exclude-dir=node_modules || true; then
          echo "Warning: Potential sensitive data found in build artifacts"
        fi 